language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

os:
  - linux
  - osx

before_script:
  - composer self-update
  - composer install -o --prefer-source
  - mkdir tests/resources/cache/
  - chmod -R 777 tests/resources/cache/

script:
  - phpunit --configuration travis.phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover --colors --verbose

after_script:
  - rm -R -f -d tests/resources/cache/
  - rmdir tests/resources/cache/
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false
